name: Django rijkshuisstijl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [2.2, 3.2]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --requirement requirements/testing.txt 
        Django==${{ matrix.django-version }}
    - name: Run the tests
      run: python -m runtests.py
